marked_quarters = 
        let
            current_date = DateTime.LocalNow(),
            current_year = Date.Year(current_date),
            current_month = Date.Month(current_date),

            // Determine the current fiscal year and quarter
            current_fiscal_year = if current_month >= 7 then current_year + 1 else current_year,
            current_fy_quarter_num = 
                if current_month >= 7 and current_month <= 9 then 1
                else if current_month >= 10 and current_month <= 12 then 2
                else if current_month >= 1 and current_month <= 3 then 3
                else 4,

            // Calculate fiscal quarter and fiscal year for 3 quarters ago
            target_fy_quarter_num = Number.Mod(current_fy_quarter_num - 3 + 4, 4),
            adjusted_target_fy_quarter_num = if target_fy_quarter_num = 0 then 4 else target_fy_quarter_num,
            target_fiscal_year = 
                if current_fy_quarter_num <= 3 then current_fiscal_year - 1
                else current_fiscal_year,

            // Mark the target rows
            result = Table.AddColumn(
                FY_quarter_num, 
                "Is Target Quarter", 
                each if [FY Quarter Num] = adjusted_target_fy_quarter_num and [FY Year] = target_fiscal_year then "Current" else null, 
                Text.Type
            )
        in
            result,