// Navigate to a second table in the same schema to use in a merge. 
// In this case, the keys data types didn't match so step 2 converts the key 
// of the dimension table into a number.

Navigate_second_table = Source{[Schema = "colostate_prod", Item = "table_name"]}[Data],

Convert_dim_table_key = Table.TransformColumns(
    Navigate_second_table, 
    {
        {"KEY", 
        each try Number.FromText(_) otherwise null, 
        type number}
    }
),

//

Merged_table = Table.NestedJoin(
        Table_1,
        {"KEY"},
        Table_2,
        {"KEY"},
        "merged_table"
    ),

Expanded_status = Table.ExpandTableColumn(
        Merged_table, 
        "merged_table", 
        {"DESCRIPTION"}, 
        {"NEWNAME"}
    ),