let
    Source = Excel.CurrentWorkbook(),
    #"Filtered Rows" = Table.SelectRows(Source, each Text.StartsWith([Name], "Query1")),
    #"Expanded Content" = Table.ExpandTableColumn(
        #"Filtered Rows",
        "Content",
        {
            "FSC_YR",
            "FSC_PRD_CD",
            "COA_CD",
            "RC_CD",
            "RC_NM",
            "ORG_CD",
            "ORG_NM",
            "SUB_FUND_CD",
            "SUB_FUND_NM",
            "ACCT_NBR",
            "ACCT_NM",
            "ACCT_FSC_OFC_NM",
            "ACCT_SPVSR_NM",
            "ACCT_MGR_NM",
            "ACCT_FSC_OFC_PRNCPL_ID",
            "ACCT_SPVSR_PRNCPL_ID",
            "ACCT_MGR_PRNCPL_ID",
            "BDGT_CTGRY_CD",
            "SUB_ACCT_NBR",
            "SUB_ACCT_NM",
            "ACCTG_CTGRY_CD",
            "OBJ_TYP_CD",
            "OBJ_CONS_CD",
            "OBJ_CONS_NM",
            "OBJ_LEVEL_CD",
            "OBJ_LEVEL_NM",
            "OBJ_CD",
            "OBJ_CD_NM",
            "SUB_OBJ_CD",
            "BEG_BAL_AMT",
            "BEG_BUD_AMT",
            "BEG_BUD_REV_AMT",
            "BEG_BUD_EXP_AMT",
            "CUR_BUD_AMT",
            "CUR_BUD_REV_AMT",
            "CUR_BUD_EXP_AMT",
            "MTD_ACTUAL_AMT",
            "YTD_ACTUAL_AMT",
            "ACTUAL_REV_AMT",
            "ACTUAL_EXP_AMT",
            "PTD_ACTUAL_AMT",
            "PROJ_REV_AMT",
            "PROJ_EXP_AMT",
            "ENCUM_AMT",
            "NET_ASSET",
            "VARIANCE",
            "CASH_BAL",
            "ASSET_AMT",
            "LIABILITY_AMT",
            "ETL_TIMESTAMP",
            "REVENUE_POSITIVE",
            "BEGINNING_BALANCE",
            "BUDGET_ENDING_BALANCE_W_ENCUM",
            "BUDGET_ENDING_BALANCE_WO_ENCUM",
            "SELF_FUNDED_BALANCE_W_ENCUM",
            "SELF_FUNDED_BALANCE_WO_ENCUM",
            "ACCT_SUB_ACCT_NBR",
            "OBJ_SUB_OBJ_CD",
            "ACCT_NBR_COA_CD",
            "EXPENSE TYPE FILTER",
            "ACCOUNT TYPE CODE",
            "HE FUNCTION CODE",
            "HE FUNCTION NAME",
            "KC SPONSOR CODE",
            "KC SPONSOR SOURCE",
            "RESEARCH REPORT CODE",
            "RESEARCH REPORT NAME"
        },
        {
            "FSC_YR",
            "FSC_PRD_CD",
            "COA_CD",
            "RC_CD",
            "RC_NM",
            "ORG_CD",
            "ORG_NM",
            "SUB_FUND_CD",
            "SUB_FUND_NM",
            "ACCT_NBR",
            "ACCT_NM",
            "ACCT_FSC_OFC_NM",
            "ACCT_SPVSR_NM",
            "ACCT_MGR_NM",
            "ACCT_FSC_OFC_PRNCPL_ID",
            "ACCT_SPVSR_PRNCPL_ID",
            "ACCT_MGR_PRNCPL_ID",
            "BDGT_CTGRY_CD",
            "SUB_ACCT_NBR",
            "SUB_ACCT_NM",
            "ACCTG_CTGRY_CD",
            "OBJ_TYP_CD",
            "OBJ_CONS_CD",
            "OBJ_CONS_NM",
            "OBJ_LEVEL_CD",
            "OBJ_LEVEL_NM",
            "OBJ_CD",
            "OBJ_CD_NM",
            "SUB_OBJ_CD",
            "BEG_BAL_AMT",
            "BEG_BUD_AMT",
            "BEG_BUD_REV_AMT",
            "BEG_BUD_EXP_AMT",
            "CUR_BUD_AMT",
            "CUR_BUD_REV_AMT",
            "CUR_BUD_EXP_AMT",
            "MTD_ACTUAL_AMT",
            "YTD_ACTUAL_AMT",
            "ACTUAL_REV_AMT",
            "ACTUAL_EXP_AMT",
            "PTD_ACTUAL_AMT",
            "PROJ_REV_AMT",
            "PROJ_EXP_AMT",
            "ENCUM_AMT",
            "NET_ASSET",
            "VARIANCE",
            "CASH_BAL",
            "ASSET_AMT",
            "LIABILITY_AMT",
            "ETL_TIMESTAMP",
            "REVENUE_POSITIVE",
            "BEGINNING_BALANCE",
            "BUDGET_ENDING_BALANCE_W_ENCUM",
            "BUDGET_ENDING_BALANCE_WO_ENCUM",
            "SELF_FUNDED_BALANCE_W_ENCUM",
            "SELF_FUNDED_BALANCE_WO_ENCUM",
            "ACCT_SUB_ACCT_NBR",
            "OBJ_SUB_OBJ_CD",
            "ACCT_NBR_COA_CD",
            "EXPENSE TYPE FILTER",
            "ACCOUNT TYPE CODE",
            "HE FUNCTION CODE",
            "HE FUNCTION NAME",
            "KC SPONSOR CODE",
            "KC SPONSOR SOURCE",
            "RESEARCH REPORT CODE",
            "RESEARCH REPORT NAME"
        }
    ),
    #"Reordered Columns" = Table.ReorderColumns(
        #"Expanded Content",
        {
            "FSC_YR",
            "ACCT_NBR",
            "ACCT_NM",
            "OBJ_CD",
            "FSC_PRD_CD",
            "COA_CD",
            "RC_CD",
            "RC_NM",
            "ORG_CD",
            "ORG_NM",
            "SUB_FUND_CD",
            "SUB_FUND_NM",
            "ACCT_FSC_OFC_NM",
            "ACCT_SPVSR_NM",
            "ACCT_MGR_NM",
            "ACCT_FSC_OFC_PRNCPL_ID",
            "ACCT_SPVSR_PRNCPL_ID",
            "ACCT_MGR_PRNCPL_ID",
            "BDGT_CTGRY_CD",
            "SUB_ACCT_NBR",
            "SUB_ACCT_NM",
            "ACCTG_CTGRY_CD",
            "OBJ_TYP_CD",
            "OBJ_CONS_CD",
            "OBJ_CONS_NM",
            "OBJ_LEVEL_CD",
            "OBJ_LEVEL_NM",
            "OBJ_CD_NM",
            "SUB_OBJ_CD",
            "BEG_BAL_AMT",
            "BEG_BUD_AMT",
            "BEG_BUD_REV_AMT",
            "BEG_BUD_EXP_AMT",
            "CUR_BUD_AMT",
            "CUR_BUD_REV_AMT",
            "CUR_BUD_EXP_AMT",
            "MTD_ACTUAL_AMT",
            "YTD_ACTUAL_AMT",
            "ACTUAL_REV_AMT",
            "ACTUAL_EXP_AMT",
            "PTD_ACTUAL_AMT",
            "PROJ_REV_AMT",
            "PROJ_EXP_AMT",
            "ENCUM_AMT",
            "NET_ASSET",
            "VARIANCE",
            "CASH_BAL",
            "ASSET_AMT",
            "LIABILITY_AMT",
            "ETL_TIMESTAMP",
            "REVENUE_POSITIVE",
            "BEGINNING_BALANCE",
            "BUDGET_ENDING_BALANCE_W_ENCUM",
            "BUDGET_ENDING_BALANCE_WO_ENCUM",
            "SELF_FUNDED_BALANCE_W_ENCUM",
            "SELF_FUNDED_BALANCE_WO_ENCUM",
            "ACCT_SUB_ACCT_NBR",
            "OBJ_SUB_OBJ_CD",
            "ACCT_NBR_COA_CD",
            "EXPENSE TYPE FILTER",
            "ACCOUNT TYPE CODE",
            "HE FUNCTION CODE",
            "HE FUNCTION NAME",
            "KC SPONSOR CODE",
            "KC SPONSOR SOURCE",
            "RESEARCH REPORT CODE",
            "RESEARCH REPORT NAME",
            "Name"
        }
    )
in
    #"Reordered Columns"
