let
    Refresh_datetime = DateTime.FixedLocalNow(),
    Converted_to_table = #table({"Last Refresh"}, {{Refresh_datetime}}),
    Changed_type = Table.TransformColumnTypes(Converted_to_table, {{"Last Refresh", type datetime}})
in
    Changed_type